### ISSUE TITLE
El sim desocupado no debería tirar error, simplemente no hace nada

### ISSUE THREAD

**Issue by Charlyzzz** [roavakian/Sims#12]

**Comment by roavakian** [comment]
Resuelto en bdfd0255e89a0fa58e4bb3fb5e36ec761692f83d

**Comment by ZabreLight** [comment]
Resuelto en:
e5bff4fb825714a1ce08525da8a48bf4db9b7421
bdfd0255e89a0fa58e4bb3fb5e36ec761692f83d
