### ISSUE TITLE
leAtrae

### ISSUE THREAD

**Issue by Charlyzzz** [roavakian/Sims#16]
Quizás sea más conveniente modelar dos objetos/clases: leGustanHombres y leGustanMujeres en vez de hombre y mujer.

Se podría apuntar a algo así
~~~
method leAtrae(otroSim){
   return self.leAtraeSuSexo(otroSim) and self.leAtraSuPersonalidad(otroSim)
}
~~~

**Comment by marinawangmw** [comment]
Hola Erwin, tengo una pregunta con respecto a este punto que tambien le consulte a Franco y me dijo que te plantee la duda. Si creamos leGustanHombres y leGustanMujeres nos quedarían los objetos femeninos y masculinos vacíos y por lo que habían preguntado los chicos no podían haber objetos vacíos y necesitamos sí o sí de femenino y masculino porque son el sexo del sim y también el sexo preferente. 
Por otro lado, ya hay objetos de personalidad porque están utilizados por otros métodos dentro del sim si lo hicieramos así estaríamos haciendo dos objetos de lo mismo.
Capaz estamos entendiendo mal la corrección así que te pedimos ayuda sobre qué es lo que se pretende que hagamos en este punto. No entendemos si queres que modifiquemos leAtrae dentro del Sim o el objeto femenino y masculino.
Saludos!

**Comment by Charlyzzz** [comment]
Yo tampoco recuerdo a que me refería. Mirar el código no me resfresca nada tampoco :/.
Lo pueden cerrar
